// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMPvdKKQrkFZoujpKKN_BwYHgBcD5vFOk',
    appId: '1:644089073502:web:3524d907ab9e0c869b09cf',
    messagingSenderId: '644089073502',
    projectId: 'fik-social-app',
    authDomain: 'fik-social-app.firebaseapp.com',
    storageBucket: 'fik-social-app.appspot.com',
    measurementId: 'G-6H5GQPGFX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTQ7uCasrIfNhR8yEjbuyGTM6LSJXurFE',
    appId: '1:644089073502:android:f524a02731066a789b09cf',
    messagingSenderId: '644089073502',
    projectId: 'fik-social-app',
    storageBucket: 'fik-social-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHR5te9YCncphT9W0ImHRTSyESn0t9FL0',
    appId: '1:644089073502:ios:4ef52851ccb4039c9b09cf',
    messagingSenderId: '644089073502',
    projectId: 'fik-social-app',
    storageBucket: 'fik-social-app.appspot.com',
    iosBundleId: 'com.example.bridgebankSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHR5te9YCncphT9W0ImHRTSyESn0t9FL0',
    appId: '1:644089073502:ios:4ef52851ccb4039c9b09cf',
    messagingSenderId: '644089073502',
    projectId: 'fik-social-app',
    storageBucket: 'fik-social-app.appspot.com',
    iosBundleId: 'com.example.bridgebankSocialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMPvdKKQrkFZoujpKKN_BwYHgBcD5vFOk',
    appId: '1:644089073502:web:2590c068f78e38f69b09cf',
    messagingSenderId: '644089073502',
    projectId: 'fik-social-app',
    authDomain: 'fik-social-app.firebaseapp.com',
    storageBucket: 'fik-social-app.appspot.com',
    measurementId: 'G-W911V5THL4',
  );
}
